version: '3'

services:
  # postgres:
  #   image: "postgres"
  #   container_name: bookwise_postgres
  #   networks:
  #     - bookwise-bridge
    
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=root      
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - /postgres-data:/var/lib/postgresql/data

  app:
    image: "bookwise/app:1.0"
    container_name: bookwise_nextjs
    networks:
      - bookwise-bridge
    ports:
      - 8080:3030

networks:
  bookwise-bridge:
    driver: bridge